remote_theme: mmistakes/so-simple-theme
locale: ko-KR
title: '공부중'
description: '풀스택 개발자가 되기 위해 공부중'
baseurl: # the subpath of your site, e.g. "/blog"
url: 'https://sangw0804.github.io' # the base hostname & protocol for your site e.g. "https://mmistakes.github.io"
logo: '/assets/images/mojave_night.jpeg' # path of site logo, e.g. "/images/logo.png"
date_format: '%B %-d, %Y'
read_time: # reading time estimates, e.g. true
words_per_minute: # 200
mathjax: # MathJax equations, e.g. true
google_fonts:
  - name: 'Source Sans Pro'
    weights: '400,400i,700,700i'
  - name: 'Lora'
    weights: '400,400i,700,700i'
google_analytics: # Google Analytics id, e.g. "UA-NNNNNNNN-N"
disqus:
  shortname: # Disqus shortname, e.g. "my_disqus_shortname"
twitter:
  username: # site's Twitter username, e.g. "mmistakes"

# Liquid
liquid:
  error_mode: strict

# Build settings
permalink: /:categories/:title/
markdown: kramdown
feed:
  path: atom.xml

# Pagination - https://jekyllrb.com/docs/pagination/
paginate: 7
paginate_path: /page:num/

# Search
search_full_content: false # can have performance implications for large sites

# Taxonomy pages
# category_archive_path: "/categories/#"
# tag_archive_path: "/tags/#"

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/

plugins:
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-paginate

# Front Matter Defaults
defaults:
  # Posts defaults
  - scope:
      path: '_posts'
      type: posts
    values:
      layout: post
      share: true

# Site Author
author:
  name: '오상우'
  picture: '/assets/images/linuxRobot.png'
  email: 'sangw0804@naver.com'
  ? twitter
  links:
    - title: GitHub
      url: 'https://github.com/sangw0804'
      icon: fab fa-github-square

# Footer Links
footer_links:
  - title: Feed
    url: atom.xml
    icon: fas fa-rss-square
  - title: GitHub
    url: 'https://github.com/sangw0804'
    icon: fab fa-github-square
